/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gazelle_boutiqe;

import com.mysql.jdbc.Connection;
import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.ResultSet;


/**
 *
 * @author Zaki_shah
 */
public class customers extends javax.swing.JFrame {

    /**
     * Creates new form customers
     */
    public customers() {
         initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         dark_mode.applyTheme(this);
         setLocationRelativeTo(null);
         name.requestFocus();
         this.revalidate();
        this.repaint();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        pro_name = new javax.swing.JTextField();
        mprice = new javax.swing.JTextField();
        discount = new javax.swing.JTextField();
        num_item = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        pro_case = new javax.swing.JTextField();
        tal = new javax.swing.JTextField();
        recive = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("customers");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        name.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 50, 0, 0);
        getContentPane().add(name, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("نام و تخلص:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 63, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("شماره تماس:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 63, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("آیدی محصول:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 63, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("نام محصول:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 63, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("قیمت اصلی:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 65, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("تخفیف:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 65, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("تعداد خرید:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 83, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("تاریخ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 83, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jCheckBox3.setText("تحفه");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 154, 0, 0);
        getContentPane().add(jCheckBox3, gridBagConstraints);

        text.setColumns(20);
        text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 712;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 33, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setBackground(java.awt.Color.blue);
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("ذخیره");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 61, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setBackground(java.awt.Color.blue);
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2.setText("پرنت");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setBackground(java.awt.Color.blue);
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/back.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -19;
        gridBagConstraints.ipady = -22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        getContentPane().add(jButton3, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel10.setText("به بخش مشتری خوش آمدید");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 198, 0, 71);
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel11.setText("developed by Code-Crafters-Company    2024");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 8, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("سایز:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 83, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("رنگ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 83, 0, 0);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setText("قالب:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 83, 0, 0);
        getContentPane().add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setText("تل:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 83, 0, 0);
        getContentPane().add(jLabel15, gridBagConstraints);

        phone.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 50, 0, 0);
        getContentPane().add(phone, gridBagConstraints);

        id.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 50, 0, 0);
        getContentPane().add(id, gridBagConstraints);

        pro_name.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pro_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_nameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 50, 0, 0);
        getContentPane().add(pro_name, gridBagConstraints);

        mprice.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpriceKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 50, 0, 0);
        getContentPane().add(mprice, gridBagConstraints);

        discount.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discountKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 50, 0, 0);
        getContentPane().add(discount, gridBagConstraints);

        num_item.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        num_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                num_itemKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 154, 0, 0);
        getContentPane().add(num_item, gridBagConstraints);

        date.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 154, 0, 0);
        getContentPane().add(date, gridBagConstraints);

        size.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        size.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sizeKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 154, 0, 0);
        getContentPane().add(size, gridBagConstraints);

        color.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colorKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 154, 0, 0);
        getContentPane().add(color, gridBagConstraints);

        pro_case.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pro_case.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_caseKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 154, 0, 0);
        getContentPane().add(pro_case, gridBagConstraints);

        tal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                talkeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 154, 0, 0);
        getContentPane().add(tal, gridBagConstraints);

        recive.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        recive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reciveKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 154, 0, 0);
        getContentPane().add(recive, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setText("رسید:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 83, 0, 0);
        getContentPane().add(jLabel16, gridBagConstraints);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("حالت شب");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement checkStmt = null;
        PreparedStatement insertStmt = null;
            String nLn=name.getText();
            String phn=phone.getText();
            double phn1=Double.parseDouble(phn);
            String dat=date.getText();
            String id1=id.getText();
            double id2=Double.parseDouble(id1);
            String pro=pro_name.getText();
            String mprice1=mprice.getText();
            double mp= Double.parseDouble(mprice1);
            String disc=discount.getText();
            double dis=Double.parseDouble(disc);
            String nitem=num_item.getText();
            double nit=Double.parseDouble(nitem);          
            String siz=size.getText();
            double size1=Double.parseDouble(siz);
            String color1=color.getText();
            //double colo=Double.parseDouble(color1);
            String pro_case1=pro_case.getText();
            //double pro_c=Double.parseDouble(pro_case1);
            String tal1=tal.getText();
            //double tl=Double.parseDouble(tal1);
            String rec=recive.getText();
            double rec1=Double.parseDouble(rec);
            
            //for chech box:
            boolean check=jCheckBox3.isSelected();
            //for calculating the total price:
            
            double total;
            double x,y,z;
            double remain1;
            x=mp;
            y=dis;
            z=nit;
            total=(x*z)-y;
            remain1=rec1-total-dis;
            String phone3=phone.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/gezele", "root","");
            String checkSql = "SELECT COUNT(*) FROM customer WHERE phone = ?";
            checkStmt = conn.prepareStatement(checkSql);
            checkStmt.setString(1, phone3);
            ResultSet rs = checkStmt.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count > 0) {
             // Duplicate found, ask user if they want to save again
            int option = JOptionPane.showConfirmDialog(null, 
            "مشتری با این شماره قبلا ذخیره شده آیا میخواهید دوباره ذخیره نمایید؟؟؟", 
            "دیتای تکراری", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
             if (option == JOptionPane.YES_OPTION) {
              // Proceed with saving the record again
            String insertSql = "INSERT into customer (name_Lname, phone, date ,id, pro_name, "
                    + "price, discount, num_item, size, color, product_case, tal ,recive, gift )"
                    + "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            insertStmt = conn.prepareStatement(insertSql);
            insertStmt.setString(1,nLn);
            insertStmt.setString(2,phn);
            insertStmt.setString(3, dat);
            insertStmt.setString(4, id1);
            insertStmt.setString(5, pro);
            insertStmt.setString(6, mprice1);
            insertStmt.setString(7, disc);
            insertStmt.setString(8, nitem);          
            insertStmt.setString(9, siz);
            insertStmt.setString(10, color1);
            insertStmt.setString(11, pro_case1);
            insertStmt.setString(12, tal1);
            insertStmt.setString(13, rec);
            insertStmt.setBoolean(14, check);
            insertStmt.executeUpdate();
             
            JOptionPane.showMessageDialog(null, 
            "ذخیره شد!!", 
            "Success", JOptionPane.INFORMATION_MESSAGE);
                
        } else {
               
            JOptionPane.showMessageDialog(null, 
            "Record not saved.", 
            "Cancelled",  JOptionPane.INFORMATION_MESSAGE);
           }
           }else {
            String sql="INSERT into customer (name_Lname, phone, date ,id, pro_name, "
                    + "price, discount, num_item, size, color, product_case, tal ,recive, gift )"
                    + "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";                     
            PreparedStatement ptst=conn.prepareStatement(sql);
            ptst.setString(1,nLn);
            ptst.setString(2,phn);
            ptst.setString(3, dat);
            ptst.setString(4, id1);
            ptst.setString(5, pro);
            ptst.setString(6, mprice1);
            ptst.setString(7, disc);
            ptst.setString(8, nitem);          
            ptst.setString(9, siz);
            ptst.setString(10, color1);
            ptst.setString(11, pro_case1);
            ptst.setString(12, tal1);
            ptst.setString(13, rec);
            ptst.setBoolean(14, check);
            

               
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this, "ذخیره شد!!");
            ptst.close();
            conn.close();
            }
        }catch( Exception ex){
            ex.printStackTrace();
            ///JOptionPane.showMessageDialog(null, "خطای دیتابیس"+ ex.getMessage());
        }
            text.setText("bill\n\n نام و تخلص مشتری  \t"+nLn+"\n شماره تماس مشتری  \t"+phn+
               "\n آیدی محصول  \t\t" +id1+"\n جنس خریداری شده \t"+pro+
               " \n  قیمت اصلی\t\t"  +mprice1+"\n تخفیف \t\t\t"+disc+
               "\n تعداد خرید \t\t"+nitem+"\nتاریخ   \t\t\t"    +dat+
               "\n سایز \t\t\t"      +siz+"\n رنگ \t\t\t"+color1+
               "\n قالب \t\t\t"      +pro_case1+"\n تل \t\t\t"+tal1+
               "\n تحفه \t\t\t"      +check+"\n رسید \t\t\t"+rec+           
               "\n\n*************************************\n مجموع \t\t\t"+total+ "\n باقی\t\t\t"+remain1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        boolean complete=text.print();
        if(complete){
            JOptionPane.showMessageDialog(null,"done printing", "bell",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "printing","printer",JOptionPane.ERROR_MESSAGE);
        }
       }catch(PrinterException ex){
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home obj=new home();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void talkeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_talkeyPressed

        // TODO add your handling code here:
                    switch(evt.getKeyCode()){
/*down*/    case 40: pro_case.requestFocus();
            break;
 /*up*/     case 38: recive.requestFocus();
            break;
/*right*/   case 39: phone.requestFocus();
            }
    }//GEN-LAST:event_talkeyPressed

    private void reciveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reciveKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
            case 40: tal.requestFocus();
            break;
            case 38: discount.requestFocus();
            break;
            case 39: name.requestFocus();
        }
    }//GEN-LAST:event_reciveKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        //40 for down---39 for right---38 for up-- 37 for left
        switch(evt.getKeyCode()){
            case 40: phone.requestFocus();
            break;
            case 37: recive.requestFocus();
            break;
        }
    }//GEN-LAST:event_nameKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
            case 40: id.requestFocus();
            break;
            case 38: name.requestFocus();
            break;
            case 37: tal.requestFocus();
        }
    }//GEN-LAST:event_phoneKeyPressed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
            case 40: pro_name.requestFocus();
            break;
            case 38: phone.requestFocus();
            break;
            case 37: pro_case.requestFocus();
        }
    }//GEN-LAST:event_idKeyPressed

    private void pro_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_nameKeyPressed
        // TODO add your handling code here:
                    switch(evt.getKeyCode()){
            case 40: mprice.requestFocus();
            break;
            case 38: id.requestFocus();
            break;
            case 37: color.requestFocus();
        }
    }//GEN-LAST:event_pro_nameKeyPressed

    private void mpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpriceKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
            case 40: discount.requestFocus();
            break;
            case 38: pro_name.requestFocus();
            break;
            case 37: size.requestFocus();
        }
    }//GEN-LAST:event_mpriceKeyPressed

    private void discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case 40: recive.requestFocus();
            break;
            case 38: mprice.requestFocus();
            break;
            case 37: date.requestFocus();
        }
    }//GEN-LAST:event_discountKeyPressed

    private void pro_caseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_caseKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
/*down*/    case 40: color.requestFocus();
            break;
 /*up*/     case 38: tal.requestFocus();
            break;
/*right*/   case 39: id.requestFocus();
            }       
    }//GEN-LAST:event_pro_caseKeyPressed

    private void colorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
/*down*/    case 40: size.requestFocus();
            break;
 /*up*/     case 38: pro_case.requestFocus();
            break;
/*right*/   case 39: pro_name.requestFocus();
            }
    }//GEN-LAST:event_colorKeyPressed

    private void sizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
/*down*/    case 40: date.requestFocus();
            break;
 /*up*/     case 38: color.requestFocus();
            break;
/*right*/   case 39: mprice.requestFocus();
            }
    }//GEN-LAST:event_sizeKeyPressed

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
/*down*/    case 40: num_item.requestFocus();
            break;
 /*up*/     case 38: size.requestFocus();
            break;
/*right*/   case 39: discount.requestFocus();
            }
    }//GEN-LAST:event_dateKeyPressed

    private void num_itemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_itemKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode()){
/*down*/    case 40: name.requestFocus();
            break;
 /*up*/     case 38: date.requestFocus();
            break;
/*right*/   case 39: discount.requestFocus();
            }        
    }//GEN-LAST:event_num_itemKeyPressed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
                                dark_mode.switchDarkmode();
        for(JFrame frame : getAllOpenFrames()){
            dark_mode.applyTheme(frame);
            frame.repaint();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed
     private java.util.List<JFrame> getAllOpenFrames(){
        java.util.List<JFrame> frames=new java.util.ArrayList<>();
        for(java.awt.Window window : java.awt.Window.getWindows()){
            if(window instanceof JFrame){
                frames.add((JFrame) window);
            }
        }
        return frames;
    }
        
    /**{
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField color;
    private javax.swing.JTextField date;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num_item;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pro_case;
    private javax.swing.JTextField pro_name;
    private javax.swing.JTextField recive;
    private javax.swing.JTextField size;
    private javax.swing.JTextField tal;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
