/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gazelle_boutiqe;

import java.awt.GridBagConstraints;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SH Hussain
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home1
     */
    public home() {
        initComponents();
        setLocationRelativeTo(null);
        dark_mode.applyTheme(this); 
         this.revalidate();
        this.repaint();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        customer1 = new javax.swing.JButton();
        customer2 = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        attend = new javax.swing.JButton();
        reports1 = new javax.swing.JButton();
        customer3 = new javax.swing.JButton();
        customer4 = new javax.swing.JButton();
        attend1 = new javax.swing.JButton();
        porduct1 = new javax.swing.JButton();
        porduct = new javax.swing.JButton();
        extras = new javax.swing.JButton();
        extras1 = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        staff1 = new javax.swing.JButton();
        sells = new javax.swing.JButton();
        sells1 = new javax.swing.JButton();
        company = new javax.swing.JButton();
        company1 = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        customer5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        customer1.setBackground(java.awt.Color.blue);
        customer1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer1.setText("سفارش مشتری");
        customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 85, 0, 0);
        getContentPane().add(customer1, gridBagConstraints);

        customer2.setBackground(java.awt.Color.blue);
        customer2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer2.setText("تحویل سفارشات");
        customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 85, 0, 0);
        getContentPane().add(customer2, gridBagConstraints);

        reports.setBackground(java.awt.Color.blue);
        reports.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reports.setText("گزارشات");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 63, 0, 0);
        getContentPane().add(reports, gridBagConstraints);

        attend.setBackground(java.awt.Color.blue);
        attend.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        attend.setText("گدام");
        attend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 85, 0, 0);
        getContentPane().add(attend, gridBagConstraints);

        reports1.setBackground(java.awt.Color.blue);
        reports1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reports1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/گزارشات.jpg"))); // NOI18N
        reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 63, 0, 0);
        getContentPane().add(reports1, gridBagConstraints);

        customer3.setBackground(java.awt.Color.blue);
        customer3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/سفارش.jpg"))); // NOI18N
        customer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        getContentPane().add(customer3, gridBagConstraints);

        customer4.setBackground(java.awt.Color.blue);
        customer4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/تحویل.jpg"))); // NOI18N
        customer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        getContentPane().add(customer4, gridBagConstraints);

        attend1.setBackground(java.awt.Color.blue);
        attend1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        attend1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/گدام.jpg"))); // NOI18N
        attend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attend1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        getContentPane().add(attend1, gridBagConstraints);

        porduct1.setBackground(java.awt.Color.blue);
        porduct1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        porduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/محصولات.jpg"))); // NOI18N
        porduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porduct1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 79, 0, 170);
        getContentPane().add(porduct1, gridBagConstraints);

        porduct.setBackground(java.awt.Color.blue);
        porduct.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        porduct.setText("محصولات");
        porduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porductActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 79, 0, 170);
        getContentPane().add(porduct, gridBagConstraints);

        extras.setBackground(java.awt.Color.blue);
        extras.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        extras.setText("مصارف");
        extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(225, 60, 0, 0);
        getContentPane().add(extras, gridBagConstraints);

        extras1.setBackground(java.awt.Color.blue);
        extras1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        extras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/مصارف.jpg"))); // NOI18N
        extras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extras1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 60, 9, 0);
        getContentPane().add(extras1, gridBagConstraints);

        staff.setBackground(java.awt.Color.blue);
        staff.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        staff.setText("کارمندان");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(225, 82, 0, 0);
        getContentPane().add(staff, gridBagConstraints);

        staff1.setBackground(java.awt.Color.blue);
        staff1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        staff1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/employee.jpg"))); // NOI18N
        staff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 82, 9, 0);
        getContentPane().add(staff1, gridBagConstraints);

        sells.setBackground(java.awt.Color.blue);
        sells.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sells.setText("فروشات");
        sells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(225, 82, 0, 0);
        getContentPane().add(sells, gridBagConstraints);

        sells1.setBackground(java.awt.Color.blue);
        sells1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sells1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/فروشات.jpg"))); // NOI18N
        sells1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sells1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 82, 0, 0);
        getContentPane().add(sells1, gridBagConstraints);

        company.setBackground(java.awt.Color.blue);
        company.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        company.setText("مشخصات شرکت");
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(225, 82, 0, 0);
        getContentPane().add(company, gridBagConstraints);

        company1.setBackground(java.awt.Color.blue);
        company1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        company1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/شرکت.jpg"))); // NOI18N
        company1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 82, 0, 0);
        getContentPane().add(company1, gridBagConstraints);

        customer.setBackground(java.awt.Color.blue);
        customer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer.setText("مشتری");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(225, 76, 0, 0);
        getContentPane().add(customer, gridBagConstraints);

        customer5.setBackground(java.awt.Color.blue);
        customer5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        customer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/customer.jpg"))); // NOI18N
        customer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 76, 0, 0);
        getContentPane().add(customer5, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazelle_boutiqe/back.jpg"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jButton4, gridBagConstraints);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("حالت شب");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer1ActionPerformed
        // TODO add your handling code here:
        spec_customer obj= new spec_customer();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customer1ActionPerformed

    private void customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer2ActionPerformed
        // TODO add your handling code here:
        recieve obj=new recieve();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customer2ActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        reports obj=new reports();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_reportsActionPerformed

    private void attendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "بزودی!!!!!");
    }//GEN-LAST:event_attendActionPerformed

    private void reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports1ActionPerformed
        // TODO add your handling code here:
        reports obj=new reports();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_reports1ActionPerformed

    private void customer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer3ActionPerformed
        // TODO add your handling code here:
        spec_customer obj= new spec_customer();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customer3ActionPerformed

    private void customer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer4ActionPerformed
        // TODO add your handling code here:
        recieve obj=new recieve();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customer4ActionPerformed

    private void attend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attend1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "بزودی!!!!!");
    }//GEN-LAST:event_attend1ActionPerformed

    private void porduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porduct1ActionPerformed
        // TODO add your handling code here:
        photo obj=new photo();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_porduct1ActionPerformed

    private void porductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porductActionPerformed
        // TODO add your handling code here:
        photo obj=new photo();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_porductActionPerformed

    private void extrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrasActionPerformed
        // TODO add your handling code here:\
        extras obj=new extras();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_extrasActionPerformed

    private void extras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extras1ActionPerformed
        // TODO add your handling code here:
        extras obj=new extras();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_extras1ActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        // TODO add your handling code here:
        staff obj=new staff();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_staffActionPerformed

    private void staff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff1ActionPerformed
        // TODO add your handling code here:
        staff obj=new staff();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_staff1ActionPerformed

    private void sellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellsActionPerformed
        // TODO add your handling code here:
        sells obj=new sells();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_sellsActionPerformed

    private void sells1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sells1ActionPerformed
        // TODO add your handling code here:
        sells obj=new sells();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_sells1ActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
        com_det obj=new com_det();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_companyActionPerformed

    private void company1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company1ActionPerformed
        // TODO add your handling code here:
        com_det obj=new com_det();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_company1ActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        customers obj=new customers();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customerActionPerformed

    private void customer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer5ActionPerformed
        // TODO add your handling code here:
        customers obj=new customers();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customer5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        login obj=new login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
                dark_mode.switchDarkmode();
        for(JFrame frame : getAllOpenFrames()){
            dark_mode.applyTheme(frame);
            frame.repaint();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed
     private java.util.List<JFrame> getAllOpenFrames(){
        java.util.List<JFrame> frames=new java.util.ArrayList<>();
        for(java.awt.Window window : java.awt.Window.getWindows()){
            if(window instanceof JFrame){
                frames.add((JFrame) window);
            }
        }
        return frames;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attend;
    private javax.swing.JButton attend1;
    private javax.swing.JButton company;
    private javax.swing.JButton company1;
    private javax.swing.JButton customer;
    private javax.swing.JButton customer1;
    private javax.swing.JButton customer2;
    private javax.swing.JButton customer3;
    private javax.swing.JButton customer4;
    private javax.swing.JButton customer5;
    private javax.swing.JButton extras;
    private javax.swing.JButton extras1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton porduct;
    private javax.swing.JButton porduct1;
    private javax.swing.JButton reports;
    private javax.swing.JButton reports1;
    private javax.swing.JButton sells;
    private javax.swing.JButton sells1;
    private javax.swing.JButton staff;
    private javax.swing.JButton staff1;
    // End of variables declaration//GEN-END:variables
}
